name: witboek-woo
baseurl:
host: 0.0.0.0
plugins: ['jekyll/minibundle']
title: >
  Woo Witboek
description: >
  'Best practices: van journalisten, voor ambtenaren'
production_url: https://woo-witboek.openstate.eu
